config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :users, only: [:show]

  devise_for :users,
             path: 'auth',
             path_names: {edit: 'profile'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :offers
  get 'tags/:tag', to: 'pages#list', as: :tag
  get '/search', to: 'pages#search'
  get '/list', to: 'pages#list'
  root 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  acts_as_taggable
  validates :user_id, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :place, presence: true

  def self.search(term)
    result = where('title LIKE ?', "%#{term}%").or where('description LIKE ?', "%#{term}%")
    result.order('id DESC')
    return result unless result.nil? && result.empty?
    order('id DESC')
  end
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :set_defaults
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :offers, dependent: :destroy
  acts_as_taggable

  has_attached_file :avatar,
                    styles: {medium: '300x300>', thumb: '100x100>'},
                    default_url: '/assets/default_profil_picture.svg'
  validates_attachment_content_type :avatar, content_type: %w[image/jpg image/jpeg image/png]

  def set_defaults
    self.enterprise = false if enterprise.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [
        :avatar,
        :enterprise,
        :username,
        :email,
        :age,
        :address,
        :phone,
        :password,
        :password_confirmation
    ])
  end

  def check_user_type(path = root_path)
    return if current_user.enterprise
    redirect_to path, notice: 'You must be an enterprise type member to access this area.'
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_offer, only: [:show, :edit, :update]
  before_action :check_user_type, only: [:new, :create, :edit]

  def index
    @offers = current_user.offers
  end

  def show
  end

  def new
    @offer = current_user.offers.build
  end

  def create
    @offer = current_user.offers.build(allowed_params)
    if @offer.save
      OfferMailer.new_offer_email(current_user, @offer).deliver_later
      redirect_to @offer, notice: 'Created offer.'
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update_attributes(params[:offer])
      redirect_to @offer, notice: 'Updated offer.'
    else
      render :edit
    end
  end

  def delete
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def allowed_params
    params.require(:offer).permit(:title, :description, :tag_list, :place)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @offers = Offer.last(3)
  end

  def list
    if params[:tag]
      @offers = Offer.tagged_with(params[:tag])
    else
      @offers = Offer.all
    end
  end

  def search
    @offers = Offer.search(params[:search])
    render 'pages/search', locals: {offers: @offers}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nice_display_of_user_options(user = current_user)
    if user_signed_in?
      render partial: 'layouts/partials/profile_options', locals: {current_user: user}
    else
      render partial: 'layouts/partials/sign_in_up'
    end
  end

  def nice_display_of_offer_options(user = current_user)
    return unless user_signed_in?
    return unless user.enterprise
    render partial: 'layouts/partials/offer_options', locals: {current_user: user}
  end

  def avatar_url(user = current_user, size = :thumb)
    if !user.avatar?
      'default_profil_picture.svg'
    else
      user.avatar.url(size)
    end
  end

  def nice_display_of_tag_list(offer = @offer)
    return unless offer.tag_list
    render partial: 'partials/tag_list', locals: {offer: offer}
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def nice_display_of_search_result(offers)
    if offers
      render partial: 'pages/partials/search_offers', locals: {offers: offers}
    else
      render partial: 'pages/partials/empty_search_offers', locals: {offers: offers}
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def nice_offers_list(user = @user)
    return unless user.offers
    render partial: 'users/partials/offers_list', locals: {user: user}
  end

  def user_profile_type(user = @user)
    user.enterprise ? 'enterprise' : 'slasher'
  end
end

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %> </li>
    <li><%= link_to "Show all offers", list_path %> </li>
    <%= nice_display_of_offer_options %>
  </ul>

  <ul>
    <%= nice_display_of_user_options %>
  </ul>
</nav>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slashershare</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render partial: 'layouts/navigation' %>
<%= yield %>
</body>
</html>

app/views/layouts/partials/_offer_options.html.erb
<li><%= link_to "My offers", offers_path %> </li>
<li><%= link_to "New offer", new_offer_path %> </li>

app/views/layouts/partials/_profile_options.html.erb
<li><%= link_to "Welcome #{current_user.username}", user_path(current_user) %></span></li>
<li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>

app/views/layouts/partials/_sign_in_up.html.erb
<li><%= link_to "Sign up", new_user_registration_path %> </li>
<li><%= link_to "Sign in", new_user_session_path %> </li>

app/views/layouts/partials/sign_in_up.html.erb
<li><%= link_to "Sign up", new_user_registration_path %> </li>
<li><%= link_to "Sign in", new_user_session_path %> </li>

app/views/offers/_form.html.erb
<%= form_for @offer, html: {multipart: true} do |f| %>
    <div>
      <%= f.label :title %><br/>
      <%= f.text_field :title, placeholder: 'Offer\'s title' %>
    </div>
    <div>
      <%= f.label :description %><br/>
      <%= f.text_area :description, placeholder: 'Offer\'s description',cols: '30', rows: '10' %>
    </div>
    <div>
      <%= f.label :place %><br/>
      <%= f.text_field :place, placeholder: '22 Jump street, Brisbane' %>
    </div>
    <div>
      <%= f.label :tag_list, 'Tags (separated by commas)' %><br/>
      <%= f.text_field :tag_list, placeholder: 'Accountant, English speaker etc...' %>
    </div>
    <div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/offers/delete.html.erb
<h1>Offers#delete</h1>
<p>Find me in app/views/offers/delete.html.erb</p>

app/views/offers/edit.html.erb
<%= render partial:'offers/form' %>

app/views/offers/index.html.erb
<%= render partial: 'partials/offers_list', locals: {offers: @offers} %>

app/views/offers/new.html.erb
<%= render partial: 'offers/form' %>

app/views/offers/show.html.erb
<% if @offer.present? %>
    <h2><%= @offer.title %></h2>
    <p><%= @offer.description %></p>
    <p><%= @offer.place %></p>
    <% if @offer.tag_list.present? %>
        <p>Tags:
          <%= raw(@offer.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %>
        </p>
    <% end %>
    <%= link_to @offer.user.username, user_path(@offer.user) %>
<% end %>

app/views/pages/home.html.erb
<%= render partial: 'partials/offers_list', locals: {offers: @offers} %>

app/views/pages/list.html.erb
<%= render partial: 'partials/offers_list', locals: {offers: @offers} %>

app/views/pages/partials/_empty_search_offers.html.erb
<h2>search empty</h2>
<%= render partial: 'partials/offers_list', locals: {offers: offers} %>

app/views/pages/partials/_search_offers.html.erb
<h2>search not empty</h2>
<%= render partial: 'partials/offers_list', locals: {offers: offers} %>

app/views/pages/search.html.erb
<%= render partial: 'partials/search', locals: {offers: offers} %>
<%= nice_display_of_search_result(offers) %>

app/views/partials/_offers_list.html.erb
<% offers.each do |offer| %>

    <h2><%= offer.title %></h2>
    <p>
      <%= truncate(offer.description, :omission => '... (View offer for full description)', :length => 180) %>
    </p>
    <%= nice_display_of_tag_list(offer) %>
    <%= link_to 'View offer', offer_path(offer) %>
    <%= link_to offer.user.username, user_path(offer.user) %>
<% end %>

app/views/partials/_search.html.erb
<%= form_tag search_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search', class: 'search', id: 'search' %>
    <%= submit_tag 'Search', class: 'btn btn-primary' %>
<% end %>

app/views/partials/_tag_list.html.erb
<p>Tags:
  <%= raw(offer.tag_list.map {|t| link_to t, tag_path(t)}.join(', ')) %>
</p>

app/views/users/partials/_enterprise_infos.html.erb
<div class=<%= "profile_type_#{type}" %>>
  <%= type.capitalize %>
</div>

app/views/users/partials/_offers_list.html.erb
<h3> See my offer:</h3>
<% user.offers.each do |offer| %>
    <div>
      <h2><%= offer.title %></h2>
      <p><%= offer.description %></p>
      <%= nice_display_of_tag_list(offer) %>
    </div>
<% end %>

app/views/users/show.html.erb
<div class=<%= "profile__#{user_profile_type}" %>>
  <h1><%= @user.username %></h1>
  <%= render partial: 'users/partials/enterprise_infos', locals: {type: user_profile_type} %>
  <%= nice_offers_list %>
</div>